# Rebuild the take-up figure and coefficient export without unrelated claim and
# policy-composition estimation. Uses the production panel and specification.
library(here)
library(data.table)
library(fixest)
source(here("program", "import", "project-params.R"))
source(here("program", "lib", "takeup-panel.R"))
source(here("program", "lib", "plot-takeup.R"))
stock <- readRDS(here("derived", "stock-county-vintage.Rds"))
stock <- stock[between(year_constr, MIN_YEAR_CONSTR, MAX_YEAR_CONSTR)]
p <- readRDS(here("derived", "nfip-balanced.Rds"))
p <- p[, .(countyfp, year_constr, mh, period_loss, policies_n,
            mandatory_purchase_policy_n)]
periods <- sort(unique(p$period_loss))
c <- readRDS(here("derived", "nfip-claims.Rds"))
c[, period_loss := ((year_loss - 1994L) %/% 5L) * 5L + 1994L]
c <- c[period_loss %in% periods & year_loss <= MAX_YEAR_LOSS,
       .(claims_n = .N), by = .(countyfp, year_constr, mh, period_loss)]
d <- build_takeup_panel(p, c, stock, periods)
ref_period <- 1992L
rhs <- " ~ i(period_constr, mh, ref = ref_period) | geo^period_loss + mh + period_constr"
fit <- function(lhs, exposure) fepois(as.formula(paste0(lhs, rhs)),
    data = if (exposure == "log_policy_yrs") d[policies_n > 0] else d,
    offset = as.formula(paste0("~", exposure)), cluster = ~statefp)
models <- list("Policies per home" = fit("policies_n", "log_home_yrs"),
               "Claims per home" = fit("claims_n", "log_home_yrs"),
               "Claims per policy" = fit("claims_n", "log_policy_yrs"))
out <- here("output", "event-study", "countyfp")
plot_takeup_event_study(models[c(1, 3)], ref_period,
                       file.path(out, "es-takeup-claim-frequency.pdf"))
# Export full precision for numerical reference alongside the figure.
coefficients <- rbindlist(lapply(names(models), function(margin) {
    ct <- as.data.table(coeftable(models[[margin]]), keep.rownames = "term")
    ct[, margin := margin]
    ct
}))
fwrite(coefficients, file.path(out, "take-up-coefficients.csv"))
# The paper's existing three-margin table is generated by estimate-nfip.R.
# Its estimates are left untouched by this figure-only rebuild.
